export const leads = [
  {
    id: 1,
    customerName: "Adani Logistics",
    sector: "Logistics",
    region: "India North",
    contactPerson: {
      name: "Ravi Sharma",
      role: "Head of Operations",
      email: "ravi.sharma@adanilogistics.com",
    },
    leadSource: "Event",
    initialUseCase: "AI-powered logistics optimization",
    inquiryType: "Direct",
    stage: "commercial",
    dealValue: 2.8,
    dealType: "PoC",
    salesOwner: "Kiran Kumar",
  },
  {
    id: 2,
    customerName: "Tata Steel",
    sector: "Manufacturing",
    region: "India East",
    contactPerson: {
      name: "Amit Patel",
      role: "CTO",
      email: "amit.patel@tatasteel.com",
    },
    leadSource: "Referral",
    initialUseCase: "Predictive maintenance for steel plants",
    inquiryType: "RFP",
    stage: "proposal",
    dealValue: 4.5,
    dealType: "Scale",
    salesOwner: "Priya Mehta",
  },
  {
    id: 3,
    customerName: "Mahindra Automotive",
    sector: "Automotive",
    region: "India West",
    contactPerson: {
      name: "Sunil Kapoor",
      role: "Innovation Director",
      email: "sunil.kapoor@mahindra.com",
    },
    leadSource: "Inbound",
    initialUseCase: "Computer vision for quality control",
    inquiryType: "Direct",
    stage: "legal",
    dealValue: 3.2,
    dealType: "Pilot",
    salesOwner: "Rahul Singh",
  },
  {
    id: 4,
    customerName: "Reliance Industries",
    sector: "Energy",
    region: "India West",
    contactPerson: {
      name: "Neha Gupta",
      role: "Head of Digital",
      email: "neha.gupta@ril.com",
    },
    leadSource: "Event",
    initialUseCase: "AI for energy optimization",
    inquiryType: "RFI",
    stage: "presentation",
    dealValue: 5.6,
    dealType: "Scale",
    salesOwner: "Vikram Desai",
  },
  {
    id: 5,
    customerName: "JSW Steel",
    sector: "Manufacturing",
    region: "India South",
    contactPerson: {
      name: "Rajesh Kumar",
      role: "Operations Manager",
      email: "rajesh.kumar@jsw.com",
    },
    leadSource: "Outreach",
    initialUseCase: "Process optimization using AI",
    inquiryType: "Direct",
    stage: "qualified",
    dealValue: 1.8,
    dealType: "PoC",
    salesOwner: "Kiran Kumar",
  },
  {
    id: 6,
    customerName: "Larsen & Toubro",
    sector: "Construction",
    region: "India West",
    contactPerson: {
      name: "Sanjay Verma",
      role: "Project Director",
      email: "sanjay.verma@lnt.com",
    },
    leadSource: "Referral",
    initialUseCase: "AI for construction site safety",
    inquiryType: "RFP",
    stage: "won",
    dealValue: 2.4,
    dealType: "Pilot",
    salesOwner: "Priya Mehta",
  },
  {
    id: 7,
    customerName: "Vedanta Resources",
    sector: "Mining",
    region: "India Central",
    contactPerson: {
      name: "Deepak Sharma",
      role: "Innovation Lead",
      email: "deepak.sharma@vedanta.com",
    },
    leadSource: "Event",
    initialUseCase: "AI for mineral exploration",
    inquiryType: "Direct",
    stage: "lost",
    dealValue: 3.7,
    dealType: "Scale",
    salesOwner: "Rahul Singh",
  },
  {
    id: 8,
    customerName: "Infosys",
    sector: "IT Services",
    region: "India South",
    contactPerson: {
      name: "Priya Nair",
      role: "VP of Innovation",
      email: "priya.nair@infosys.com",
    },
    leadSource: "Inbound",
    initialUseCase: "AI solutions for client services",
    inquiryType: "RFI",
    stage: "commercial",
    dealValue: 4.2,
    dealType: "Partnership",
    salesOwner: "Vikram Desai",
  },
  {
    id: 9,
    customerName: "Bharat Petroleum",
    sector: "Oil & Gas",
    region: "India West",
    contactPerson: {
      name: "Anil Joshi",
      role: "Digital Transformation Head",
      email: "anil.joshi@bpcl.com",
    },
    leadSource: "Outreach",
    initialUseCase: "AI for refinery optimization",
    inquiryType: "Direct",
    stage: "proposal",
    dealValue: 3.9,
    dealType: "Pilot",
    salesOwner: "Kiran Kumar",
  },
  {
    id: 10,
    customerName: "Wipro Limited",
    sector: "IT Services",
    region: "India South",
    contactPerson: {
      name: "Vikram Malhotra",
      role: "Director of AI Solutions",
      email: "vikram.malhotra@wipro.com",
    },
    leadSource: "Referral",
    initialUseCase: "Enterprise AI implementation",
    inquiryType: "RFP",
    stage: "presentation",
    dealValue: 2.9,
    dealType: "Scale",
    salesOwner: "Priya Mehta",
  },
  {
    id: 11,
    customerName: "Maruti Suzuki",
    sector: "Automotive",
    region: "India North",
    contactPerson: {
      name: "Rahul Khanna",
      role: "Manufacturing Head",
      email: "rahul.khanna@maruti.com",
    },
    leadSource: "Event",
    initialUseCase: "AI for production line optimization",
    inquiryType: "Direct",
    stage: "qualified",
    dealValue: 1.5,
    dealType: "PoC",
    salesOwner: "Rahul Singh",
  },
  {
    id: 12,
    customerName: "Hindustan Unilever",
    sector: "FMCG",
    region: "India West",
    contactPerson: {
      name: "Meera Patel",
      role: "Supply Chain Director",
      email: "meera.patel@hul.com",
    },
    leadSource: "Inbound",
    initialUseCase: "AI for demand forecasting",
    inquiryType: "RFI",
    stage: "won",
    dealValue: 2.2,
    dealType: "Pilot",
    salesOwner: "Vikram Desai",
  },
]
